export const configRegistration = {
    keys: [
        'title_name',
        'first_name',
        'last_name',
        'phone',
        'gender',
        'nationality',
        'country',
        'province',
        'religion',
        'marital_status',
        'blood_group',
        'occupation',
        'mother_title_name',
        'mother_first_name',
        'mother_last_name',
        'father_title_name',
        'father_first_name',
        'father_last_name',
        'allergy',
        'datetime',
    ],
};
